name: '$(Build.BuildId)'
variables:
  BUILD_CONFIGURATION: 'Release'
jobs:
- job:
  displayName: 'Auction Buddy CI'
  pool:
    vmImage: 'macOS-10.14'
  workspace:
    clean: 'all'
  steps:
  - script: npm install --global yarn
    displayName: 'Install Yarn'
  - script: yarn install
    displayName: 'Install dependencies'
  - script: yarn ci
    displayName: 'Run CI'