name: '$(Build.BuildId)'
variables:
  BUILD_CONFIGURATION: 'Release'

resources:
  containers:
  - container: sql_server
    image: 'microsoft/mssql-server-linux'
    ports:
    - 1401:1433
    env:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'ThisIsAStrongPassword!'
      
jobs:
- job: 1
  displayName: 'Install docker'
  steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

- job: 2
  displayName: 'Auction Buddy CI'
  dependsOn: 1
  pool:
    vmImage: 'macOS-10.14'

  workspace:
    clean: 'all'

  services:
    sql_server: sql_server

  steps:
  - task: NodeTool@0
    displayName: 'Install Node 10'
    inputs:
      versionSpec: 10.x

  - script: npm install --global yarn@1.16.0
    displayName: 'Install Yarn'

  - script: npm install --global azure-functions-core-tools@2.7.1158
    displayName: 'Install Azure Functions Core Tools'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn ci
    displayName: 'Run CI'