name: $(Build.BuildId)
stages:
  - stage: build_and_test
    displayName: Build and Test
    jobs:
      - job: ci
        displayName: Continuous Integration
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - script: dotnet restore
            displayName: Restore NuGet Packages

          - task: UseNode@1
            displayName: Install Node 10
            inputs:
              versionSpec: 10.x

          - script: npm install -g yarn
            displayName: Install Yarn

          - script: yarn
            displayName: Install Node packages
            workingDirectory: $(Build.SourcesDirectory)/tests/Auction.Buddy.Acceptance

          - script: dotnet dev-certs https --trust
            displayName: Trust Dev Certificates

          - script: dotnet test
            displayName: Run Dotnet Unit Tests
          
          - script: yarn test
            displayName: Run Acceptance Tests
            workingDirectory: $(Build.SourcesDirectory)/tests/Auction.Buddy.Acceptance

  - stage: deploy_app
    displayName: Deploy Auction Buddy
    jobs:
      - job: deploy
        displayName: Deploy
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: dotnet restore
            displayName: Restore NuGet Packages

          - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/auciton-buddy
            displayName: Publish Auction Buddy Api
            workingDirectory: $(Build.SourcesDirectory)/src/Auction.Buddy.Api